config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :pqr_trackings
  resources :statuses
  resources :pqrs
  resources :docs
  devise_for :users
  get 'home/index' 
  resources :departments
  resources :permission_roles
  resources :roles
  resources :permissions
  resources :users
  resources :admins  
  get '/users_json', to: 'users_json#metodo'  
  get '/pqr_trackingsDepartment', to: 'pqr_trackings#departmentView'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:status_description)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="card">
  <div class="card hoverable" style="background-color: rgba(255,255,255,.15);" id="card-login">
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-content grey lighten-4">
  <div class="field">
    <%= form.label :status_description %>
    <%= form.select(:status_description, [['No revisado', 'no_revisado'], ['En espera', 'en_espera'], ['Finalizado', 'finalizado'], ['Vencido', 'vencido']]) %>
  </div>

  </div>
  <div class="actions  card-action center-align">
    <%= form.submit "Enviar",class:'btn btn-large waves-effect waves-light blue darken-3 hoverable pulse ',:style => "color: white !important; " %>
  </div>
<% end %>
</div>
</div>  

app/views/statuses/edit.html.erb
<% if can? :update, Status%>

<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/statuses/index.html.erb
<% if can? :read, Status%>
<p id="notice"><%= notice %></p>

<h1 class="center">Statuses</h1>
<div class="row">
  <div class="col l12">
    <%= link_to 'New Status', new_status_path, class: 'waves-effect waves-light btn cyan' %>
  </div>
</div>
<div class="card">
  
<table class="striped">
  <thead>
    <tr>
      <th class="center">Status description</th>
      <th class="center">Edit</th>
      <th class="center">Delete</th>
    </tr>
    
      
    
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td class="center"><%= status.status_description %></td>
        <td class="center"><%= link_to 'Editar', edit_status_path(status), class: 'waves-effect waves-light btn green',:style => "color: white !important;"  %></td>
        <td class="center"><%= link_to 'Eliminar', status, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red',:style => "color: white !important;"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %> 

app/views/statuses/new.html.erb
 <% if can? :create, Status%>

<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>
<%else%>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %> 
<script>
$(document).ready(function(){
    $('select').formSelect();

  });
</script>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status description:</strong>
  <%= @status.status_description %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>