config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :pqr_trackings
  resources :statuses
  resources :pqrs
  resources :docs
  devise_for :users
  get 'home/index' 
  resources :departments
  resources :permission_roles
  resources :roles
  resources :permissions
  resources :users
  resources :admins  
  get '/users_json', to: 'users_json#metodo'  
  get '/pqr_trackingsDepartment', to: 'pqr_trackings#departmentView'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doc.rb
class Doc < ApplicationRecord
    has_many :pqrs 
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = Doc.new
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:url)
    end

    
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<div class="card">
  <div class="card hoverable" style="background-color: rgba(255,255,255,.15);" id="card-login">
<%= form_with(model: doc, local: true) do |form| %>
  <% if doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-content grey lighten-4">
      <div class="field">
        <%= form.label :url %>
        <%= form.file_field :url %>
      </div>
  </div>
  <div class="actions  card-action center-align">
    <%= form.submit "Enviar",class:'btn btn-large waves-effect waves-light blue darken-3 hoverable pulse ',:style => "color: white !important; " %>
  </div>
<% end %>
</div>
</div>  

app/views/docs/edit.html.erb
<% if can? :update, Doc%>
<h1>Editing Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/docs/index.html.erb
<% if can? :read, Doc%>
<p id="notice"><%= notice %></p>
<div class="center">
    <h1>Docs</h1>
</div>
    <%= link_to 'Nuevo Archivo', new_doc_path, class: 'waves-effect waves-light btn cyan',:style => "color: white !important;"  %>
<div class="card">
  
<table class="striped">
  <thead>
    <tr>
      <th class="center">Url</th>
      <th class="center">Editar</th>
      <th class="center">Eliminar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td class="center"><%= doc.url %></td>
        <td class="center"><%= link_to 'Editar', edit_doc_path(doc), class: 'waves-effect waves-light btn green',:style => "color: white !important;"  %></td>
        <td class="center"><%= link_to 'Eliminar', doc, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red',:style => "color: white !important;"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/docs/new.html.erb
<<<<<<< HEAD
<% if can? :create, Doc%>
=======
<% if can? :create, Status%>
>>>>>>> 61bbf2d3ac62d9811896a6ff0e629d2bfbdc49dd
<h1>New Doc</h1>

<%= render 'form', doc: @doc %>

<%= link_to 'Back', docs_path %>
<<<<<<< HEAD
<% else %>
   <script type="text/javascript">
         window.location.href="/"
   </script>
=======

>>>>>>> 61bbf2d3ac62d9811896a6ff0e629d2bfbdc49dd
<% end %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @doc.url %>
</p>

<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>