config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :pqr_trackings
  resources :statuses
  resources :pqrs
  resources :docs
  devise_for :users
  get 'home/index' 
  resources :departments
  resources :permission_roles
  resources :roles
  resources :permissions
  resources :users
  resources :admins  
  get '/users_json', to: 'users_json#metodo'  
  get '/pqr_trackingsDepartment', to: 'pqr_trackings#departmentView'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permission_role.rb
class PermissionRole < ApplicationRecord
  belongs_to :permission
  belongs_to :role
end

app/controllers/permission_roles_controller.rb
class PermissionRolesController < ApplicationController
  before_action :set_permission_role, only: [:show, :edit, :update, :destroy]

  # GET /permission_roles
  # GET /permission_roles.json
  def index
    @permission_roles = PermissionRole.all
  end

  # GET /permission_roles/1
  # GET /permission_roles/1.json
  def show
  end

  # GET /permission_roles/new
  def new
    @permission_role = PermissionRole.new
  end

  # GET /permission_roles/1/edit
  def edit
  end

  # POST /permission_roles
  # POST /permission_roles.json
  def create
    @permission_role = PermissionRole.new(permission_role_params)

    respond_to do |format|
      if @permission_role.save
        format.html { redirect_to @permission_role, notice: 'Permission role was successfully created.' }
        format.json { render :edit, status: :created, location: @permission_role }
      else
        format.html { render :new }
        format.json { render json: @permission_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permission_roles/1
  # PATCH/PUT /permission_roles/1.json
  def update
    respond_to do |format|
      if @permission_role.update(permission_role_params)
        format.html { redirect_to @permission_role, notice: 'Permission role was successfully updated.' }
        format.json { render :new, status: :ok, location: @permission_role }
      else
        format.html { render :edit }
        format.json { render json: @permission_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permission_roles/1
  # DELETE /permission_roles/1.json
  def destroy
    @permission_role.destroy
    respond_to do |format|
      format.html { redirect_to permission_roles_url, notice: 'Permission role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission_role
      @permission_role = PermissionRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_role_params
      params.require(:permission_role).permit(:permission_id, :role_id)
    end
end

app/helpers/permission_roles_helper.rb
module PermissionRolesHelper
end

app/views/permission_roles/_form.html.erb
<div class="card">
  <div class="card hoverable" style="background-color: rgba(255,255,255,.15);" id="card-login">
<%= form_with(model: permission_role, local: true) do |form| %>
  <% if permission_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission_role.errors.count, "error") %> prohibited this permission_role from being saved:</h2>

      <ul>
      <% permission_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-content grey lighten-4">
  <div class="field">
    <%= form.select "permission_id", Permission.all.collect {|x| [x.description, x.id]},{}, class: "multiple"%>
  </div>

  <div class="field">
    <%= form.select "role_id", Role.all.collect {|x| [x.name, x.id]},{}, class: "multiple"%>
  </div>
  
  </div>
  <div class="actions  card-action center-align">
    <%= form.submit "Enviar",class:'btn btn-large waves-effect waves-light blue darken-3 hoverable pulse ',:style => "color: white !important; " %>
  </div>
<% end %>
</div>
</div>  

app/views/permission_roles/edit.html.erb
<% if can? :update, PermissionRole%>
<h1>Editing Permission Role</h1>

<%= render 'form', permission_role: @permission_role %>

<%= link_to 'Show', @permission_role %> |
<%= link_to 'Back', permission_roles_path %>
<% else %>
   <script type="text/javascript">
         window.location.href="/"
   </script>
<% end %>

app/views/permission_roles/index.html.erb
<% if can? :read, PermissionRole%>
<p id="notice"><%= notice %></p>

<h1 class="center">Permisos de Roles</h1>
    <%= link_to 'Nuevo Permiso de rol', new_permission_role_path, class: 'waves-effect waves-light btn cyan'  %>
<div class="card">
  
<table class="striped">
  <thead>
    <tr>
      <th class="center">Permission</th>
      <th class="center">Role</th>
      <th class="center">Editar</th>
      <th class="center">Eliminar</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permission_roles.each do |permission_role| %>
      <tr>
        <td class="center"><%= permission_role.permission.description %></td>
        <td class="center"><%= permission_role.role.name %></td>
        <td class="center"><%= link_to 'Editar', edit_permission_role_path(permission_role), class: 'waves-effect waves-light btn green',:style => "color: white !important;"  %></td>
        <td class="center"><%= link_to 'Eliminar', permission_role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red',:style => "color: white !important;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/permission_roles/new.html.erb
<% if can? :create, PermissionRole%>

<h1>New Permission Role</h1>

<%= render 'form', permission_role: @permission_role %>

<%= link_to 'Back', permission_roles_path %>
<% else %>
   <script type="text/javascript">
         window.location.href="/"
   </script>
<% end %>

app/views/permission_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Permission:</strong>
  <%= @permission_role.permission %>
</p>

<p>
  <strong>Role:</strong>
  <%= @permission_role.role %>
</p>

<%= link_to 'Edit', edit_permission_role_path(@permission_role) %> |
<%= link_to 'Back', permission_roles_path %>