config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :pqr_trackings
  resources :statuses
  resources :pqrs
  resources :docs
  devise_for :users
  get 'home/index' 
  resources :departments
  resources :permission_roles
  resources :roles
  resources :permissions
  resources :users
  resources :admins  
  get '/users_json', to: 'users_json#metodo'  
  get '/pqr_trackingsDepartment', to: 'pqr_trackings#departmentView'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :doc,optional: true
  has_and_belongs_to_many :pqr_trackings
end

app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]

  # GET /pqrs
  # GET /pqrs.json
  def index
    @pqrs = Pqr.all
  end

  # GET /pqrs/1
  # GET /pqrs/1.json
  def show
  end

  # GET /pqrs/new
  def new
    @pqr = Pqr.new
  end

  # GET /pqrs/1/edit
  def edit
  end

  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = Pqr.new(pqr_params)

    respond_to do |format|
      if @pqr.save
        format.html { redirect_to @pqr, notice: 'Pqr was successfully created.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
      @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:first_name, :last_name, :email, :title, :subject, :description, :date, :response_date, :doc_id)
    end
end

app/helpers/pqrs_helper.rb
module PqrsHelper
end

app/views/pqrs/_form.html.erb
<div class="card">
  <div class="card hoverable" style="background-color: rgba(255,255,255,.15);" id="card-login">
<%= form_with(model: pqr, local: true) do |form| %>
  <% if pqr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr.errors.count, "error") %> prohibited this pqr from being saved:</h2>

      <ul>
      <% pqr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="card-content grey lighten-4">
  <div class="row">
    <div class="field col s12 l12">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="field col s12 l6">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>
  <div class="row">
    <div class="field col s12 l6  ">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>
    
  </div>  
  </div>
  <div class="row">
      <div class="field col s12 l6">
            <%= form.label :email %>
            <%= form.text_field :email %>
      </div>
        <div class="field col s12 l6">
            <%= form.label :subject %>
            <%= form.text_field :subject %>
        </div>
  </div>
  <div class="row">
    
    <div class="field col s12 l6">
      <%= form.label :description %>
      <%= form.text_area :description%>
    </div>
    <div class="field col s12 l6 ">
      <%= form.label :doc_id %> <br> <br>
      <%= form.file_field :doc_id %>
    </div>

  </div>
    <div class="field col s12 l6" style="display:none;">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>

  <div class="field" style="display:none;">
    <%= form.label :response_date %>
    <%= form.date_select :response_date, class:'datepicker' %>
  </div>
  


  </div>
  <div class="actions  card-action center-align">
    <%= form.submit "Enviar",class:'btn btn-large waves-effect waves-light blue darken-3 hoverable pulse ',:style => "color: white !important; " %>
  </div>
<% end %>
</div>
</div>  

app/views/pqrs/edit.html.erb
<% if can? :update, Pqr%>
<h1>Editing Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Show', @pqr %> |
<%= link_to 'Back', pqrs_path %>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/pqrs/index.html.erb
<% if can? :read, Pqr%>
<p id="notice"><%= notice %></p>

<h1 class="center">PQRS</h1>
    <%= link_to 'Nuevo Pqr', new_pqr_path, class: 'waves-effect waves-light btn cyan'%>
<div class="card">
  
<table class="striped">
  <thead>
    <tr>
      <th class="center">First name</th>
      <th class="center">Last name</th>
      <th class="center">Email</th>
      <th class="center">Title</th>
      <th class="center">Subject</th>
      <th class="center">Description</th>
      <th class="center">Date</th>
      <th class="center">Response date</th>
      <th class="center">Doc</th>
      <th class="center">Editar</th>
      <th class="center">Eliminar</th>

      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pqrs.each do |pqr| %>
      <tr>
        <td class="center"><%= pqr.first_name %></td>
        <td class="center"><%= pqr.last_name %></td>
        <td class="center"><%= pqr.email %></td>
        <td class="center"><%= pqr.title %></td>
        <td class="center"><%= pqr.subject %></td>
        <td class="center"><%= pqr.description %></td>
        <td class="center"><%= pqr.date %></td>
        <td class="center"><%= pqr.response_date %></td>
        <td class="center"><%= pqr.doc %></td>
        <td class="center"><%= link_to 'Editar', edit_pqr_path(pqr), class: 'waves-effect waves-light btn green',:style => "color: white !important;" %></td>
        <td class="center"><%= link_to 'Eliminar', pqr, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red',:style => "color: white !important;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %>

app/views/pqrs/new.html.erb
<% if can? :create, Pqr%>
<h1 class="center">Crear PQR</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Back', pqrs_path %>
<% else %>
<script type="text/javascript">
    window.location.href="/"
</script>
<% end %> 

app/views/pqrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @pqr.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pqr.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pqr.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pqr.title %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @pqr.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pqr.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @pqr.date %>
</p>

<p>
  <strong>Response date:</strong>
  <%= @pqr.response_date %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @pqr.doc %>
</p>

<%= link_to 'Edit', edit_pqr_path(@pqr) %> |
<%= link_to 'Back', pqrs_path %>